<?xml version="1.0" encoding="utf-8"?>
<File>
  <Version>2.1</Version>
  <Variables>
    <ArrayOfVariable xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <Variable>
        <Name>Index</Name>
        <InitialValue>0</InitialValue>
        <Scope>Private</Scope>
        <ShowScopeProperty>true</ShowScopeProperty>
        <DebuggerVisible>true</DebuggerVisible>
      </Variable>
      <Variable>
        <Name>Length</Name>
        <Scope>Private</Scope>
        <ShowScopeProperty>true</ShowScopeProperty>
        <DebuggerVisible>true</DebuggerVisible>
      </Variable>
      <Variable>
        <Name>Digits</Name>
        <ShowScopeProperty>true</ShowScopeProperty>
        <DebuggerVisible>true</DebuggerVisible>
      </Variable>
    </ArrayOfVariable>
  </Variables>
  <Flows>
    <MainFlow>
      <ns0:MainFlow Description="Callflow execution path." DebugModeActive="False" x:Name="Component1" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:ns0="clr-namespace:TCX.CFD.Classes.Components;Assembly=3CX Call Flow Designer, Version=16.4.26.0, Culture=neutral, PublicKeyToken=7cb95a1a133e706e">
        <ns0:PromptPlaybackComponent AcceptDtmfInput="True" DebugModeActive="False" PromptList="&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;ArrayOfPrompt xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Prompt xsi:type=&quot;TextToSpeechAudioPrompt&quot;&gt;&lt;VoiceName&gt;Joanna&lt;/VoiceName&gt;&lt;Format&gt;Text&lt;/Format&gt;&lt;Text&gt;&quot;The Support ID you have entered is&quot;&lt;/Text&gt;&lt;/Prompt&gt;&lt;/ArrayOfPrompt&gt;" x:Name="ID_Verification" />
        <ns0:VariableAssignmentComponent VariableName="callflow$.Length" DebugModeActive="False" Expression="LEN(callflow$.Digits)" x:Name="Digit_Length" />
        <ns0:LoopComponent Condition="LESS_THAN(callflow$.Index,callflow$.Length)" Description="Execution path when the specified condition is met." DebugModeActive="False" x:Name="Read_Single_Digit">
          <ns0:PromptPlaybackComponent AcceptDtmfInput="True" DebugModeActive="False" PromptList="&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;ArrayOfPrompt xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Prompt xsi:type=&quot;TextToSpeechAudioPrompt&quot;&gt;&lt;VoiceName&gt;Joanna&lt;/VoiceName&gt;&lt;Format&gt;Text&lt;/Format&gt;&lt;Text&gt;MID(callflow$.Digits,callflow$.Index,1)&lt;/Text&gt;&lt;/Prompt&gt;&lt;/ArrayOfPrompt&gt;" x:Name="Read_Digit" />
          <ns0:IncrementVariableComponent DebugModeActive="False" VariableName="callflow$.Index" x:Name="IncrementIndex" />
        </ns0:LoopComponent>
      </ns0:MainFlow>
    </MainFlow>
    <ErrorHandlerFlow>
      <ns0:ErrorHandlerFlow Description="Execution path when an error ocurrs." DebugModeActive="False" x:Name="Component1" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:ns0="clr-namespace:TCX.CFD.Classes.Components;Assembly=3CX Call Flow Designer, Version=16.4.26.0, Culture=neutral, PublicKeyToken=7cb95a1a133e706e" />
    </ErrorHandlerFlow>
    <DisconnectHandlerFlow>
      <ns0:DisconnectHandlerFlow Description="Execution path since the call gets disconnected." DebugModeActive="False" x:Name="Component1" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:ns0="clr-namespace:TCX.CFD.Classes.Components;Assembly=3CX Call Flow Designer, Version=16.4.26.0, Culture=neutral, PublicKeyToken=7cb95a1a133e706e" />
    </DisconnectHandlerFlow>
  </Flows>
</File>